name = "SankeyPlots"
uuid = "8fd88ec8-d95c-41fc-b299-05f2225f2cc5"
authors = ["Daniel Schwabeneder <daschw@disroot.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
